name: repondfred
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  intl: ^0.18.1
  universal_html: ^2.2.1
  geolocator: ^14.0.2
  font_awesome_flutter: ^10.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo2.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/logo2.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/


